name: Build and publish
on:
  push:
    branches: [main]
jobs:

  Build-and-upload-apps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
      working-directory: taskpane-app
    - run: npm run build
      working-directory: taskpane-app
    - name: Upload app
      uses: armhil/azure-blobs-content-uploader@1.0.4
      with:
        azureBlobConfiguration: ${{ secrets.AZ_BLOB_CONFIGURATION }}
        directoriesToUpload: '[
          {"path": "taskpane-app/build", "baseContainerPath": "easy-qrcode-barcode/taskpane", "shouldRecurse": true },
          {"path": "submission/images", "baseContainerPath": "easy-qrcode-barcode/images", "shouldRecurse": false }]'