name: Build and publish
on:
  push:
    branches: [main]
jobs:
  Build-and-upload-apps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
      working-directory: taskpane-app
    - run: npm test -- --coverage
      working-directory: taskpane-app
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: armhil/easy-qrcode-barcode-addin
    - name: Update build date
      run: |
        DATE=$(date +'%Y-%m-%d %H:%M')
        sed -i "s/REPLACE_BUILD_DATE/$DATE/" taskpane-app/src/build-date.ts
    - run: npm run build
      working-directory: taskpane-app
    - name: Create PR for build artifacts
      run: |
        TARGET_REPO="https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/armhil/armhil.github.io.git"
        # Clone the target repository into a folder named "target-repo"
        git config --global user.email "arman.hilmioglu@gmail.com"
        git config --global user.name "armhil"
        git clone "$TARGET_REPO" target-repo
        cd target-repo
        # Create a new branch with a timestamp-based name
        BRANCH="add-build-artifacts-$(date +%s)"
        git checkout -b "$BRANCH"
        # Copy build artifacts from current workspace into the target repo folder
        cp -R ../taskpane-app/build/index.html ./easy-qrcode-barcode/taskpane/index.html
        cp -R ../taskpane-app/build/static/js/main.js ./easy-qrcode-barcode/taskpane/static/js/main.js
        cp -R ../taskpane-app/build/static/css/main.css ./easy-qrcode-barcode/taskpane/static/css/main.css
        cp -R ../submission/images/* ./easy-qrcode-barcode/images/
        cp -R ../submission/documents/* ./easy-qrcode-barcode/documents/
        git add .
        # Check if there are staged changes
        if git diff --staged --quiet; then
          echo "No changes to commit. Exiting."
          exit 0
        else
          git commit -m "Add build artifacts from easy-qrcode-barcode-addin build"
          git push origin "$BRANCH"
          # Authenticate GitHub CLI using the secret token
          echo "${{ secrets.TARGET_REPO_TOKEN }}" | gh auth login --with-token
          # Create a pull request targeting the main branch
          gh pr create --title "Add Build Artifacts from easy-qrcode-barcode-addin" --body "This PR includes the latest build artifacts." --base main
        fi
